baseURL        = "/"
title          = "hugo-pure"
languageCode   = "en-us"

[menu]
  [[menu.main]]
    identifier = "home"
    url        = "/"
    title      = "Home"
    weight     = 1
  [[menu.main]]
    identifier = "posts"
    url        = "/posts/"
    title      = "Posts"
    weight     = 5
